'$schema' = 'https://starship.rs/config-schema.json'
palette = "catppuccin_mocha"
add_newline = false

format = """
$os$directory${custom.prompt_symbol}
"""

[fill]
symbol = " "

[character]
disabled = true

[custom.prompt_symbol]
command = "if [ \"$(id -u)\" -eq 0 ]; then printf '#'; else printf '$'; fi"
format = "$output "
shell = ["bash", "--noprofile", "--norc"]
when = "true"

[username]
format = "$user"
show_always = true
style_user = 'white bold'
style_root = 'red bold'
disabled = true

[hostname]
ssh_only = false
ssh_symbol = ' ssh://'
format = "$ssh_symbol$hostname"
trim_at = "."
style = "plain"
disabled = false

[directory]
truncate_to_repo = false
style = "plain"
format = "$path "
truncation_length = 1

[time]
disabled = false
time_format = "%H:%M"
style = "fg:crust bg:blue"
format = "[  $time ]($style)"

# Palette definitions
[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

# Symbol definitions
[aws]
symbol = '  '

[buf]
symbol = ' '

[c]
format = '[─](fg:current_line)[](fg:blue)[$symbol](fg:primary bg:blue)[](fg:blue bg:box)[ $version](fg:foreground bg:box)[](fg:box)'
symbol = ' C'

[cmake]
symbol = ' '

[conda]
disabled = false
ignore_base = true
format = '[─](fg:base)[](fg:green)[$symbol](fg:primary bg:green)[](fg:green bg:box)[ $environment](fg:foreground bg:box)[](fg:box)'
symbol = ' '

[crystal]
symbol = ' '

[custom.svn_global]
symbol = " "
description = "Show SVN (global) revision when visiting a WC"
when = "svn --non-interactive info >/dev/null 2>&1"
command = "svn --non-interactive info --no-newline --show-item revision"
 
[custom.svn_local]
symbol = " "
description = "Show SVN last-changed-revision for the current working directory when visiting a WC"
when = "svn --non-interactive info >/dev/null 2>&1"
command = "svn --non-interactive info --no-newline --show-item last-changed-revision"
 
[custom.svn_status]
symbol = " "
description = "Show a summary of SVN status flags for the current working directory when visiting a WC"
when = "svn --non-interactive info >/dev/null 2>&1"
command = "~/starship-svn-status.sh"

[dart]
symbol = ' '

[docker_context]
disabled = false
only_with_files = true
format = '[─](fg:base)[](fg:cyan)[$symbol](fg:primary bg:cyan)[](fg:cyan bg:box)'
symbol = ' docker'

[dotnet]
format = '[─](fg:current_line)[](fg:purple)[$symbol](fg:primary bg:purple)[](fg:purple bg:box)[ $tfm](fg:foreground bg:box)[](fg:box)'
symbol = ' .NET'

[elixir]
symbol = ' '

[elm]
symbol = ' '

[erlang]
symbol = "ⓔ "

[fennel]
symbol = ' '

[fossil_branch]
symbol = ' '

[git_branch]
style = "fg:crust bg:mauve"
format = "[[](fg:mauve)[  $symbol$branch ]($style)[](fg:mauve)] "

[git_status]
style = "fg:peach bg:surface0"
format = "[[](fg:surface0)[ $all_status$ahead_behind ]($style)[](fg:surface0)] "

[git_metrics]
disabled = false
format = ' [+$added]($added_style)/[-$deleted]($deleted_style) '
added_style = 'green'

[git_commit]
tag_symbol = '  '

[golang]
symbol = ' '

[guix_shell]
symbol = ' '

[haskell]
symbol = ' '

[haxe]
symbol = ' '

[hg_branch]
symbol = ' '

[java]
format = '[─](fg:current_line)[](fg:red)[$symbol](fg:primary bg:red)[](fg:red bg:box)[ $version](fg:foreground bg:box)[](fg:box)'
symbol = ' Java'

[julia]
symbol = ' '

[kotlin]
symbol = ' '

[lua]
symbol = ' '

[memory_usage]
symbol = '󰍛 '

[meson]
symbol = '󰔷 '

[nim]
symbol = '󰆥 '

[nix_shell]
symbol = ' '

[nodejs]
format = '[─](fg:current_line)[](fg:green)[$symbol](fg:primary bg:green)[](fg:green bg:box)[ $version](fg:foreground bg:box)[](fg:box)'
symbol = '󰎙 Node.js'

[ocaml]
symbol = ' '

[os]
disabled = false
format = "$symbol "

[os.symbols]
Alpaquita = ' '
Alpine = ' '
AlmaLinux = ' '
Amazon = ' '
Android = ' '
Arch = ' '
Artix = ' '
CachyOS = ' '
CentOS = ' '
Debian = ' '
DragonFly = ' '
Emscripten = ' '
EndeavourOS = ' '
Fedora = ' '
FreeBSD = ' '
Garuda = ' '
Gentoo = ' '
HardenedBSD = '󰞌 '
Illumos = '󰈸 '
Kali = ' '
Linux = ' '
Mabox = ' '
Macos = ' '
Manjaro = ' '
Mariner = ' '
MidnightBSD = ' '
Mint = ' '
NetBSD = ' '
NixOS = ' '
Nobara = ' '
OpenBSD = ' '
OpenCloudOS = ' '
openEuler = ' '
openSUSE = ' '
OracleLinux = '⊂⊃ '
Pop = ' '
Raspbian = ' '
Redhat = ' '
RedHatEnterprise = ' '
RockyLinux = ' '
Redox = '󰀘 '
Solus = ' '
SUSE = ' '
Ubuntu = ' '
Unknown = ' '
Void = ' '
Windows = ' '

[package]
symbol = '󰏗 '

[perl]
symbol = ' '

[php]
symbol = ' '

[pijul_channel]
symbol = ' '

[python]
format = '[─](fg:current_line)[](fg:green)[$symbol](fg:primary bg:green)[](fg:green bg:box)[ $version](fg:foreground bg:box)[](fg:box)'
symbol = ' python'

[rlang]
symbol = '󰟔 '

[ruby]
symbol = ' '

[rust]
symbol = '󱘗 '

[scala]
symbol = ' '

[swift]
symbol = ' '

[typst]
symbol = "t "

[zig]
symbol = ' '

[gradle]
symbol = ' '
